### ISSUE TITLE
Running cnn_generate.py requires 2016.04C.multisnr.pkl

### ISSUE THREAD

**Issue by danbudanov** [chrisruk/models#1]
Please point to where this pickle file can be found.

**Comment by danbudanov** [comment]
If a link to the dataset at https://radioml.com/datasets/radioml-2016-04-dataset/ could be provided in the documentation it would be very helpful.

**Comment by chrisruk** [comment]
Thanks for pointing that out, I will add that into the readme file.  

Please note that the FAM model was what I was concentrating on before.  I need to work on the CNN model again, as the accuracy is lower than it should be.  

I need to find out why there is a reduction in accuracy from my TFlearn version, to the Keras version.
